### ISSUE TITLE
Channel Key Support

### ISSUE THREAD

**Issue by naiaokami** [RITlug/teleirc#129]
It would make sense to add support for channel keys (passwords) on +k channels.

**Comment by Tjzabel** [comment]
@naiaokami thanks for the issue! This is definitely something we can look into.

**Comment by acy** [comment]
Hi. Any ideas on what it would take to implement this properly?

I'm currently running teleirc on a channel with a key, and so far the only change I had to make was to fiddle with this check, since the configured channel has the key in it, but the actual one doesn't: 
`if (channel.toLowerCase() !== this._ircConfig.channel.toLowerCase()) {`
in [IrcMessageHandler:42](https://github.com/RITlug/teleirc/blob/36b10eeeb196a680f0fd0fa556c9176f889e40dd/lib/IrcHandlers/IrcMessageHandler.js#L42)

**Comment by Tjzabel** [comment]
@acy hello! Thanks for adding an update to this issue. We are currently on "break" for the summer, and only making fixes to breaking updates until we pick back up in mid-August. You can see what issues we are currently working on [here](https://github.com/RITlug/teleirc/projects/1?fullscreen=true). 

In terms of a workaround, what you described is essentially what I would have done as well. This doesn't seem like a very difficult issue, but we have not yet thought about any sort of implementation as of yet. If you have any ideas, feel free to let us know ^.^

**Comment by Tjzabel** [comment]
As an update, I looked into the IRC library we use to see if there is support for channels that require password authentication.

I am unsure if the functionality exists, and I have asked for further clarification. I will let you know the result of the conversation :+1:

**Comment by Tjzabel** [comment]
Added via 1f4039a9a259e9fc384063b0effa47099a57a425

Let me know if there are any further issues!
