### ISSUE TITLE
Consider supporting nodemon in development environments

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#140]
## What this is
[Nodemon](https://nodemon.io/) is a nodejs tool to watch file changes, and restarts the service when any file changes occur. 

## What it looks like
`nodemon [--watch .env] teleirc.js`
By default, nodemon watches the current directory, excluding any dot files. You can add an optional `--watch` parameter to specify any other files (such as the `.env`) that are left out.

## Outcome
Using nodemon, if a change occurs to any file while TeleIRC is operating, the bot restarts, taking into account the newer changes. 

## How
* Install nodemon: `npm install nodemon`
* Replace `node` with `nodemon` in the startup

**Comment by jwflory** [comment]
@Tjzabel This is interesting. I wonder how this affects packaging for those who use `systemd` unit files to manage TeleIRC. Could you describe the process a sysadmin follows to upgrade and restart the bot with `nodemon` and `systemctl`?

I wonder if automatic detection of changes is desired behavior?

**Comment by Tjzabel** [comment]
@jwflory the purpose of nodemon is for automatic detection of changes. 

Using the systemd service file, you can still use `systemctl restart` if needed. 
Using nodemon itself, typing `rs` in the terminal will make nodemon restart the program. 

For upgrading:
1. Run `nodemon teleirc.js` in one window, and have a second fresh window to `git pull`
2. Do the `git pull` to get the newest changes
3. nodemon automatically restarts once it detects changes to any files in the directory

**Comment by Tjzabel** [comment]
The main use I've seen for nodemon is in docker containers, where developers share the directory as a volume, and use nodemon to restart the application when files are updated. This means docker doesn't need to be restarted each time a change happens, contrary to normal container development processes.

**Comment by jwflory** [comment]
@Tjzabel I'm not sure this is desired behavior. If you deploy a container on bare-metal, this makes sense. But when you use a container orchestration tool like Kubernetes (k8s), usually a new "good" container is created and it replaces the old container. This lets you roll back to a known good configuration (or container).

I believe we should cater towards a k8s use case. This is a nice idea and I understand why it is useful, but there are likely more pressing issues in our backlog to work on. What do you think?

**Comment by jrtechs** [comment]
I've use nodemon before and it works great for development where you don't constantly want to restart the server manually. This might be dicey to use for production because of node packages that might need to be fetched/updated for a new code release.

A well maintained update/install script _might_ be the right route to go if you plan on having a bunch of updates.
A update script would probably do the following:
- checks if there is an update
- stops service
- makes a backup
- pulls from git
- updates node packages
- runs unit tests
  - tells user if any system dependencies are not meet
  - give option to restore backup if tests fail
- restart the service

Idk, I would highly encourage you guys to use nodemon for development. If stable and easy updates are a concern to you guys, I can possibly throw my hat into the race for this one. I have been considering making something like this for a few of my node projects.

**Comment by jwflory** [comment]
Hi @jrtechs, thanks for weighing in! :+1: 

> A well maintained update/install script might be the right route to go if you plan on having a bunch of updates.

I'm not sure we will have many updates. We usually push out a git tag once every months. For feature releases (e.g. `v1.x`), there may be new functionality that requires human intervention to upgrade (e.g. adding or changing a setting to the config file).

> restart the service

Since in the end, the service is still restarted (i.e. the bot will disconnect from Telegram and IRC and cause a brief moment of disruption), I think this creates a problem for us to solve. When I replied to @Tjzabel, I mentioned the containers use case to ensure continuous uptime (i.e. a container running an old version is "replaced" by a new container running the latest version). Since this is what our deployment "story" is, I'm not sure where `nodemon` fits into that.

It's not that I don't see this as useful for local development, but I feel like if we support `nodemon`, it is only useful for local development instead of a production deployment. Therefore, I am not sure it is worth the development time to work on this.

Does my point of view make sense? I'm curious to know what others think. If I can understand the value this brings to either or both (1) day-to-day development and (2) production deployment methods, I could be convinced.

**Comment by Tjzabel** [comment]
@jwflory @jrtechs I think there is a slight misunderstanding here. I am only considering using nodemon for local development.

I wasn't planning on this being a large change. Simply adding an npm script entry into `package.json` to support nodemon in development, and possibly adding nodemon into dev images so docker can properly be used for development purposes as well, was all I had in mind.

**Comment by Tjzabel** [comment]
This issue came to mind for me when I was constantly stopping/starting TeleIRC as I was doing development.

**Comment by jwflory** [comment]
@Tjzabel I first read this issue as a change in how we primarily run the application (i.e. instead of `node teleirc.js`). If this only affects the development environment and also does not affect how the application is deployed, then I think this is fine.
