### ISSUE TITLE
It's possible hide the "nodebot"

### ISSUE THREAD

**Issue by DiegoDAF** [RITlug/teleirc#145]
Hi, when the bot connecto to the irc channel I see the connection message:

-!- teleirc [~**nodebot**@190.216.73.194] has joined #bsdar

It's possible hide or change the string "nodebot"? 
because, all who want to attack us know what is nodebot
 
Thanks a lot,
Diego

**Comment by Tjzabel** [comment]
Hm, so this not something that is reasonable or necessary to do. You can:
1. Disable join/leave messages
2. Rename the nodebot to something else

However, the entire purpose of TeleIRC is that it routes traffic from one platform to the other. Any time a message comes from Telegram to IRC, nodebot will be the user that relays those messages. It's not a bot that you will see only once when it's joining the bridge. 

Knowing that there's a TeleIRC bot running isn't much of an attack vector itself, and would point more towards a badly managed server rather than TeleIRC itself, if it were to get infiltrated from knowing nodebot is running at `190.216.73.194`.

**Comment by DiegoDAF** [comment]
Hi Tim! 

Yes, I see, but after ask again in the group, They told me the "whois" is showing **realname : nodeJS IRC client** and that is the problem.

```[14:23] == bsdarbot [~nodebot@190.216.73.194]
[14:23] ==  realname : nodeJS IRC client
[14:23] ==  channels : #bsdar
[14:23] ==  server   : verne.freenode.net [Amsterdam, NL, EU]
[14:23] == End of WHOIS```

**Comment by DiegoDAF** [comment]
I change it on:

node_modules/irc/lib/irc.js
and 
node_modules/irc/docs/API.rst

**Comment by Tjzabel** [comment]
@DiegoDAF I still don't see what the issue is. Anyone can run a `whois` on a server. It's still not much of an attack. All I'm getting from that is that it's a nodeJS bot running in that channel, which you would already know just from being in that channel.

I would like to know what your specific concerns are with this?

**Comment by Tjzabel** [comment]
Due to the nature of the TeleIRC bot, and bots in general, the bot name *has* to be available, since the bot is the user that is actually relaying traffic over the bridge. There is no way to hide the bot name, nor is there a good enough reason to.

@DiegoDAF thanks for bringing this issue up nonetheless! It's always good to have a conversation about security :+1:

**Comment by jwflory** [comment]
Hi all! Security concerns aside, I think this is worth considering. We have a ticket already open, #113, that would cover this issue.

The fields @DiegoDAF refer to are for the `ident` and `realname` fields in an IRC connection. My guess is the IRC Node library we use sets defaults for `nodebot` and `nodeJS IRC client`. This should be fairly trivial to override and add new configuration options to our `env` file for the user to change and configure as they wish.

I would actually like to override these values and include our own defaults about TeleIRC to better promote our project if someone doesn't care about the default value. But in some cases, users may want to override this as something else, either for security-by-obscurity or for more unique customization.

I won't re-open this specific issue, but I will make a note of this in #113 so we can cover it whenever that ticket gets worked on.

@DiegoDAF Thanks for bringing this up and thanks @Tjzabel for responding quickly here.
