### ISSUE TITLE
Long usernames cut short Telegram side

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#148]
## Example
```
<desnudopenguino[>    tjzabel oh! nice
```
## Issue
In the message displayed above, `desnudopenguino[m]` does not have his full username shown. 

## Solution
Figure out where we do username creation, and figure out if we have a max username size, and see if we need to increase the max username size.

**Comment by Tjzabel** [comment]
It's a *possibility* that `TgMessageHandler.js` may inadvertently be creating this issue:
```
let username = '\x02' + TgHelpers.ResolveUserName(from) + '\x02';
        const messagePrefix = self._ircConfig.prefix + username + self._ircConfig.suffix + " ";
        const messageSplitRegex = new RegExp(`.\{1,${self._ircConfig.maxMessageLength - messagePrefix.length}}`, 'g');

        // split messages based on max message length, and prepend username on each new line
        userMessage.toString().split(/\r?\n/).filter(function(line) {
          return line.length > 0;
        }).forEach(function(line) {
          var linesToSend = line.match(messageSplitRegex);
          linesToSend.forEach(function(toSend) {
            self._action(messagePrefix + toSend);
          });
        });
    }
}
```
This code block is doing a lot of splitting/filtering in order to get the multi-line formatting to work correctly. This is a possible starting point.

**Comment by jwflory** [comment]
@Tjzabel Did we verify this in vanilla IRC? I think this might be a limitation of Riot, not TeleIRC.

When I connect to my IRC client, I also see @desnudopenguino's username as `desnudopenguino[`. This is because Riot sets its username only in Matrix. It uses a different nick to connect to Freenode unless you manually change it (see _Setting your IRC nick_ in [this article](https://opensource.com/article/17/5/introducing-riot-IRC)). In this case, I think this is a character cap set by Freenode / IRC instead of being trimmed by TeleIRC.

Let me know if you have a chance to test this. I'm on a firewalled network but I can try later today or tomorrow from home.

**Comment by Tjzabel** [comment]
@jwflory ah, makes sense. So it looks to be more of an issue that Matrix has a longer username length cap than IRC. If that's the case, then this issue may not have a fix.
