### ISSUE TITLE
Add space after (edited) in edited Telegram messages

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#153]
This is a super pedantic issue, but when someone edits a message:
```
<T​jzabel> My message
<T​jzabel> (edited)My edited message
```

There should be a space between `(edited)` and the start of the message.

**Comment by jwflory** [comment]
Ahh, I noticed this too! I think it only happens when using a non-default edit message. In the case of the channels you and I are both in where I configured a non-default value, I did add the whitespace, but somehow it gets trimmed out.

A better implementation might be to hard-code the whitespace into TeleIRC, so an end-user doesn't have to remember to include it anyways for it to work.

**Comment by Tjzabel** [comment]
@jwflory ah, thanks for the clarification. I wasn't aware this was solely a non-default value issue.

**Comment by jwflory** [comment]
I would bet this could be fixed by adding whitespace here:

https://github.com/RITlug/teleirc/blob/36b10eeeb196a680f0fd0fa556c9176f889e40dd/lib/TelegramHandlers/TgEventListener.js#L83-L87

And removing whitespace here:

https://github.com/RITlug/teleirc/blob/36b10eeeb196a680f0fd0fa556c9176f889e40dd/config.js#L21

**Comment by Tjzabel** [comment]
That's most likely the fix :+1:

**Comment by Tjzabel** [comment]
Fixed in commit 3a401d4d1b39c36904287bc5b1ccb484b0ed2454
