### ISSUE TITLE
Implement Unified Message Handling between IRC and Telegram

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#212]
Here is the outcome of our discussions on how to best create the unfiied structure:
```Go
(...)

tgClient, _ := tg.NewClient(settings.Telegram)
tgChan := make(chan error)

ircClient := irc.NewClient(settings.IRC)
ircChan := make(chan error)

go ircClient.StartBot(ircChan, tg.SendMessage)
go tgClient.StartBot(tgChan, irc.SendMessage)

(...)
```

_Originally posted by @Tjzabel in https://github.com/RITlug/teleirc/issues/198#issuecomment-549101020_

**Comment by jwflory** [comment]
@Tjzabel Are you targeting this issue for the current sprint or a next sprint? Please update this card on the project board when you have a chance. Thanks!

**Comment by jwflory** [comment]
No new updates over break. This issue is a focus of the next sprint.

The Telegram side is somewhat more complicated because of third-party library. @Tjzabel is researching how sending is done on Telegram to higher level of abstraction, so we can send any text object across the bridge.

## Closing criteria

- [ ] Send simple text message from one platform to the other

---

Related to #210.

**Comment by Tjzabel** [comment]
We now have a complete TeleIRC bridge working in Go :tada: :tada:
