### ISSUE TITLE
Determine how TeleIRC starts from environment variables

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#219]
# Summary

We can potentially simplify our `LoadConfig` error handling.

# Background

**Is your improvement related to a problem? Please describe**:

WIthin our `LoadConfig` function, the `godotenv.Load` function takes care of error handling, and so therefore we can remove all of our error handling from our end. However, this can only be done if we do not wish to use only environment variables (no `.env` file) to start up TeleIRC.

**Describe the solution you'd like**:

If we only want to support pulling environment variables from the `.env` file, then we should remove our unnecessary error handling, since that is all taken care of for us.

**Describe alternatives you've considered**:

If we *do* want to support pulling only from environment variables, then we need to add a flag to the startup of TeleIRC, and we need to create an alternative check to make sure we don't check for a `.env` file.

# Details

Our next steps are to determine whether or not we want to support pulling environment variables directly, without the use of a config file. This would then mean the user would be providing the variables on the command line, and so we would need to do more error handling. Currently, our environment variable error handling occurs during the initial reading of the config file.

# Outcome

We have clear understanding on how exactly we wish to obtain the information required for the health of TeleIRC.

**Comment by jwflory** [comment]
I think we need to understand the use case better and start with more research. Why would we want to pull in config settings as environment variables instead of the `.env` file? If I wanted to deploy TeleIRC as a container to an existing OpenShift environment, what is the best way for me to do that? The answers to these questions should motivate our decision.

**Comment by Zedjones** [comment]
Totally late to this conversation, but one reason would be using something like Docker Compose. With Compose, you can provide a .env file as an option and everything inside will be loaded into environment variables within the container. Otherwise, you'd have to copy a .env file into the container beforehand.

**Comment by jwflory** [comment]
Here's some of my notes from today:

* Reviewed [The Twelve-Factor App](https://12factor.net/)
  * See [_Config_](https://12factor.net/config)
  * See [_Processes_](https://12factor.net/processes)
* How is config data handled in containers and container orchestration?
  * Kubernetes has [ConfigMaps](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)
  * Specifically, you can create ConfigMaps [from static files like an env file](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files)
  * So, it would be possible to pull a portable container from a container registry and rebuild it with a set of env vars passed from a file
* Since we are looking at OpenShift, how does OpenShift work?
  * [Fedora Communishift](https://fedoraproject.org/wiki/Infrastructure/Communishift) runs OpenShift v4.1
  * OpenShift has/had ConfigMaps too, but I could only find [docs for v3.11](https://docs.openshift.com/container-platform/3.11/dev_guide/configmaps.html)
  * OpenShift 4 docs mentions [image configuration resources](https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html), but not clear if this is what we want

My first analysis is that we will want to keep loading in environment variables from a file. When we publish the container to a container registry, it will be with the "defaults" in the `env.example` file. For a downstream user, they will configure a set of k8s/openshift resources to rebuild the container with their own env vars.

Still needs a deeper look and I realize my k8s knowledge is a few years rusty, but this is a start. Next steps will probably be to crawl through GitHub for examples of other Go apps deployed in containers and see how they handle config data.

**Comment by jwflory** [comment]
_[Discussed in 2020-03-14 meeting](https://bluejeans.com/s/O5ssq/)._

---

Closing criteria for this is whether OpenShift ConfigMaps can be created from `env` files. If yes, we don't need to make changes to our project and we can keep chugging along. If no, we'll need to consider other ways to accept env vars as config data.

I aim to close this research out in the next few days.

**Comment by jwflory** [comment]
I have 90% confidence that it is possible to create OpenShift ConfigMaps from `env` files. Closing as complete, and I do not suggest changing our approach on how we handle configuration.

It is definitely possible in [OpenShift v3.2](https://docs.openshift.com/enterprise/3.2/dev_guide/configmaps.html#configmaps-creating-from-files), but the section in the documentation disappeared in v4 versions. However, there is an example of [creating a ConfigMap from a file in the CLI](https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-keystone-identity-provider.html#identity-provider-creating-configmap_configuring-keystone-identity-provider) for an unrelated example. So I am pretty sure this will still be possible in Fedora Communishift, which is running OpenShift v4.1.

I also asked for advice on `#fedora-admin` and it was suggested to me that the OpenShift client tools should be about the same, so this was further validation for me that we should be safe to assume this is doable going forward.
