### ISSUE TITLE
Open new issues for more handlers

### ISSUE THREAD

**Issue by jwflory** [RITlug/teleirc#244]
As per the developer call today, we need more issues for handlers in the current sprint!

**Comment by Tjzabel** [comment]
### Update
At this point, I believe all IRC handlers now have issues associated with them.

Next step is to create issues for Telegram handlers.

**Comment by Tjzabel** [comment]
I've created IRC + Telegram handler issues that should hold us for a bit. Once we have these initial handlers implemented, then we can start making the message handlers fancier, and adding the functionality we need.

Since all handlers now have issues associated with them, I feel this issue has met the closing criteria.

**Comment by jwflory** [comment]
Thanks @Tjzabel! :+1:
