### ISSUE TITLE
Documentation improvement re install/deploy

### ISSUE THREAD

**Issue by aNullValue** [RITlug/teleirc#297]
this is a copypasta of pertinent parts of a conversation between myself and @Tjzabel and @jwflory .

i didn't know that "Read the Docs" had a version selector. in all of the years that i've used RTD, i'd not noticed it until @Tjzabel provided someone else a link to a specific-version document yesterday. realizing that was incredibly helpful. 

but also, the "Quick Install" and "How to deploy TeleIRC" documents seem... inadequate on their own. IME/IMO most people do not separate the concepts of installation from deployment. like at all. those of you who work with node/go every day may well keep those as separate concepts, but i certainly don't. if you continue to have them as separate documents, please at least describe their interaction on each page; i've worked in ops for nearly 20 years, so i probably understand their relationship better than others might. 

also, the systemd service file linked from the docs is missing. i _eventually_ found it, just now, by cloning the repo and looking at commit history to see if it had changed or where it had gone. turns out it's just been moved, as part of a commit that references Go (and hence v2) (it's now at deployments/systemd/teleirc.service), despite its content still referencing v1.

## Maintainer checklist (_edited_)

- [x] ~~Add callout for older docs versions~~ 1bf5ad6c054ec768a4a25eb12167ff58a477a238
- [x] ~~Merge "Quick install" / "How to deploy" doc into a single Quick Start page~~ ae6adeeeb5979560a39391796e9c17e9923a2a8f
- [ ] Correctly document systemd / bare metal approach to deployment
- [x] ~~Make sure all version strings are updated and correct~~ 71177fab7713aed63136f37325b7cf427733ab92

**Comment by jwflory** [comment]
@aNullValue Thanks for opening this issue! :+1: 

> i didn't know that "Read the Docs" had a version selector. in all of the years that i've used RTD, i'd not noticed it until @Tjzabel provided someone else a link to a specific-version document yesterday. realizing that was incredibly helpful.

My first thought is adding a list with links to versioned docs on the index page so it's more obvious to someone that we have versioned docs. I forget the dropdown menu in the corner is not obvious if you aren't familiar with RTD already.

> IME/IMO most people do not separate the concepts of installation from deployment.

Once our v2.0.0 deployment bits are ironed out in #193, I can work on this. Agreed on a point that came up in chat:

"IME multiple methods is fine, but each method needs to be its own doc, from beginning to end, so that the end-administrator doesn't need to understand a supportability matrix."

**Comment by jwflory** [comment]
Working on this today. Also, systemd changes/improvements landed in #317.

**Comment by jwflory** [comment]
_Discussed in [2020-05-23 meeting](https://bluejeans.com/s/kF2he)._

---

## Release-blocking: _YES_

This issue is release-blocking. The fourth and final step outlined in the original comment (documenting `systemd` deployment method) is all that is left. The container instructions won't make it into this release, but we will revisit once our container is more battle-tested.

Expect a PR from me in 1-2 hours.
