### ISSUE TITLE
Write unit tests for the update handler

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#306]
# Summary

Unit tests do not currently exist for the update handler.

# Background

**Is your improvement related to a problem? Please describe**:

After writing the update handler, it is unclear if we have handled all edge cases. We should have unit tests to thoroughly test the update handler functionality.

**Describe the solution you'd like**:

Full set of unit tests for the update handler to catch as many edge cases as we can.

**Describe alternatives you've considered**:

No alternatives.

# Details

The owner of this issue needs to think of what the update handler should support, and not support. Then, build unit tests around the desired and undesired functionality to make sure error handling exists in the appropriate locations.

# Outcome

Unit testing encompasses the update handler. Allows us to feel safe knowing the update handler has been thoroughly tested.

**Comment by jwflory** [comment]
* _Metadata edited_:
    * **Milestone** (`v2.x.x` :arrow_right: `v2.0.1`)

**Comment by jwflory** [comment]
_Discussed in [2020-11-15 meeting](https://youtu.be/LwxS54qLg5U)._

---

We talked this one through in our meeting tonight, and like #314, we came to the conclusion that there is not much more we can feasibly test here. In order to test parts of this code, we would need to set up chat servers or mock out several complex network responses. The cost in testing is greater than the value it would bring to day-to-day development.

Closing as `wontfix`.
