### ISSUE TITLE
Implement unit testing for irc.go

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#314]
## Summary
Before we write unit tests for the main `irc.go` file, we need to determine the method of testing that works best for the scope of this file. 

Since `irc.go` makes heavy use of external libraries and functionality, we need to have a way to properly mock all of these external calls so we can efficiently test the desired functionality.

**Comment by jwflory** [comment]
_Discussed in [2020-05-23 meeting](https://bluejeans.com/s/kF2he)._

---

## Release-blocking: _No_

#319 was a higher priority and this didn't make it into the v2.0.0 release window. We will rescope this issue and target it for a new release in next week's meeting.

**Comment by jwflory** [comment]
* _Metadata edited_:
    * **Milestone** (`v2.x.x` :arrow_right: `v2.0.1`)

**Comment by jwflory** [comment]
What is needed for this issue that is not already covered in the existing tests?

https://github.com/RITlug/teleirc/blob/master/internal/handlers/irc/irc_test.go

**Comment by jwflory** [comment]
_Discussed in 2020-11-01 IRC/Telegram meeting_.

---

The testing sprint begins! @Zedjones is taking this one on since he has the most prior experience working with the IRC side of things.

**Comment by jwflory** [comment]
_Discussed in [2020-11-15 meeting](https://youtu.be/LwxS54qLg5U)._

---

We talked this one through, and without setting up an actual IRC server to test with, there is not much more we can do on this one. In the meeting, we agreed to close this as `wontfix` because the cost of creating tests is greater than the benefit they would bring us. IRC functionality is sufficiently tested.
