### ISSUE TITLE
Add support for multiple IP addresses to TeleIRC

### ISSUE THREAD

**Issue by CP1832** [RITlug/teleirc#324]
Dear colleagues:

I am checking with you as my Teleirc is to be hosted on a shell that has several IP addresses available and I was wondering if it is possible to specify which one will be used by Teleirc. Would it be possible to add support for theis feature?

**Comment by jwflory** [comment]
While working on #355, I discovered that a fix for this issue is fairly trivial. I have the changes for this issue saved locally, but it will be easier to open a Pull Request after #355 is merged. I made many structural changes to the docs and `env.example` which means… merge conflicts galore. 😛 

Anyways, this will definitely make it in the v2.1.0 window. PR coming soon.

**Comment by jwflory** [comment]
Added in PR #356.

**Comment by jwflory** [comment]
@CP1832 Keep an eye out for this feature in v2.1.0 coming within the next week.
