### ISSUE TITLE
Determine how best to display TeleIRC version flag

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/teleirc#346]
# Summary

Every time we make a new release of TeleIRC, we need to make sure we are also updating the TeleIRC versioning flag.

# Background

**Is your improvement related to a problem? Please describe**:

Users were confused on our latest `v.2.0.1` release, as our versioning flag still says `v2.0`.

**Describe the solution you'd like**:

We need to make sure our versioning flag correctly reflects the most up to date release. Therefore, this should always be the latest change we make before we cut a new release.

**Describe alternatives you've considered**:

None. This needs to happen.

**Comment by jwflory** [comment]
_Discussed in [2020-10-25 meeting](https://youtu.be/V4UaDtmRrfQ)_.

---

We discussed a short-term way to solve this, which @Zedjones is working on for this ticket. We also discussed a long-term way to solve this.

## Short-term

Create an executable script to create a TeleIRC release and [inject a build-time variable](https://blog.alexellis.io/inject-build-time-vars-golang/) for the TeleIRC release, determined by the latest git tag on TeleIRC. To obtain the release variable, we can use this command in the script:

```bash
git tag -l | tail -n 1
```

## Long-term

Use GitHub Actions and GitHub Packages to publish the release. Ideally, this uses some of the heavy-lifting automation steps discussed in #343. It would be great to leverage an automated pipeline with a simple interface, instead of a long list of steps that an individual developer must remember and complete in the right order.

**Comment by jwflory** [comment]
Fixed in #352 by @Zedjones.

Long-term discussion will continue in #343 as part of release planning.
