### ISSUE TITLE
Add code convention recommendations

### ISSUE THREAD

**Issue by thenaterhood** [RITlug/teleirc#73]
We should consider adding a code style guide so teleirc code is consistent. This makes approaching things in the project easier because there's consistent code format throughout. This also would make it possible to add linting.

I'd recommend this one as it's relatively commonly used, but there are other options as well. https://github.com/airbnb/javascript

**Comment by jwflory** [comment]
_Discussed in [2020-03-07 meeting](https://bluejeans.com/s/jQvmg/)._

---

For the v2.x.x release, this issue is not about linting (see #256). The code style code is a one-page doc that covers more semantics that are specific to our project. To track this, a list of those things is below:

- [ ] Naming conventions
- [ ] Patterns for writing new handlers
- [ ] Interfaces

**Comment by jwflory** [comment]
_Discussed in [2020-04-11 meeting](https://bluejeans.com/s/RViMY)._

---

I updated the issue title to focus more on what this is. Since our CI pipeline already enforces things like `gofmt` and `golint`, style is not a huge concern for documentation. However, the "human" semantics of how we do things like in the [last post](https://github.com/RITlug/teleirc/issues/73#issuecomment-596137188) are better examples of what goes into a doc like this.

To reiterate, this doc will probably not be very long. If we keep to the three sections outlined in the last comment, it might be 2-3 sentences for each section. It should not be a very verbose doc.
